### ISSUE TITLE
'unbound variable' when variable is set in a shell-hook

### ISSUE THREAD

**Issue by expipiplus1** [xzfc/cached-nix-shell#15]
When entering a shell with a package which sets an env variable in a shell hook cached nix shell fails with the error 'unbound variable'

To reproduce:

```
$ cached-nix-shell -p vulkan-validation-layers
cached-nix-shell: updating cache
/nix/store/23qgk9g5bcsjf5bq0akcs76iw7b533f7-vulkan-validation-layers-1.2.131.2/nix-support/setup-hook: line 1: XDG_DATA_DIRS: unbound variable
cached-nix-shell: nix-shell: exit code: 1
```

**Comment by expipiplus1** [comment]
Well, I suppose bash fails with this message technically

**Comment by xzfc** [comment]
In this particular case, the error is caused by a setupHook that tries to read an impure variable.
It reproducible by `nix-shell --pure -p vulkan-validation-layers`.

**Comment by xzfc** [comment]
This particular case could be handled by passing `--keep` explicitly (added in 0e73944dc31132d2aa9a769f4cc677eea6984bec):
`cached-nix-shell --keep XDG_DATA_DIRS -p vulkan-validation-layers`

**Comment by expipiplus1** [comment]
Ah, I didn't know about keep!

Thanks again for the useful tool!

**Comment by xzfc** [comment]
> Ah, I didn't know about keep!

I added it just now. 😅

**Comment by expipiplus1** [comment]
Thanks! Using it already :)
