### ISSUE TITLE
Stranged HOME_PATH format

### ISSUE THREAD

**Issue by blaggacao** [xzfc/cached-nix-shell#17]
https://github.com/direnv/direnv/issues/654#issue-664915055

@xzfc would you agree to have a quick look at what I observed when using with direnv? Maybe you can see at first sight why a few `\n` are inserted where direnv doesn't expect them and if it's legit and on which part to fix?

**Comment by xzfc** [comment]
It seems that you have `shellHook` in `shell.nix` that echoes extra lines to stdout?

It's a bug in `cached-nix-shell`: it doesn't expect anything extra in the output of `nix-shell --run 'env -0'`. I'll fix it. In the meantime, you can wrap `shellHook` into `{` … `} 1>&2` to redirect its output to stderr.

**Comment by blaggacao** [comment]
Yep:
```
    export KUBECTL_EXTERNAL_DIFF=delta
    git config git-town.code-hosting-driver gitea
    git config git-town.code-hosting-origin-hostname git.p1.rocks
    git config git-town.main-branch-name master
    just help
```

I print out the just help recipe for better onboarding. Your analysis is spot-on black magic. Thank you! :+1: 

```console
$ nix-shell --run 'env -0'
warning: unknown setting 'experimental-features'
nix-pre-commit-hooks: hooks up to date



# -------------------------------------
# Task Runner
# -------------------------------------
# show recipes with: `just --list`


# -------------------------------------
# Conventional Commits
# -------------------------------------
# Only well-formatted commits shall
# land in master branch.
# -------------------------------------
# `cz commit` to commit
# `cz info` to show the info
# `cz schema` to show the schema
# `cz example` to show an example


# -------------------------------------
# GitTown for collaboration
# -------------------------------------
# `git town sync` - synch everything
# `git town hack` - start new feature
# `git town` - list all commands


HOST_PATH[...]
```

**Comment by blaggacao** [comment]
`just help 1>&2` worked around! Thank you!

**Comment by xzfc** [comment]
Should be fixed in the current `master`.

**Comment by blaggacao** [comment]
It is fixed. Thank you! Looks so much better :smile: !
