### ISSUE TITLE
Does not understand <nixpkgs> references

### ISSUE THREAD

**Issue by nh2** [xzfc/cached-nix-shell#21]
It seems it doesn't understand `<variable>` references yet, is that correct?

Works in `nix-shell`:

```sh
NIX_PATH= nix-shell -I nixpkgs=/etc/nixos/nixpkgs '<nixpkgs>' -A procps
```

Does not work in `cached-nix-shell`:

```sh
NIX_PATH= cached-nix-shell -I nixpkgs=/etc/nixos/nixpkgs '<nixpkgs>' -A procps
```

(I repro with `NIX_PATH=` to empty that variable, to avoid the `<nixpkgs>'` import potentially working due to some other system-dependent reason.)

**Comment by xzfc** [comment]
Thanks for the report. Both #21 and #22 should be fixed in master branch.

**Comment by nh2** [comment]
Thanks!
