### ISSUE TITLE
Different behaviour from nix-shell wrt `pipefail`

### ISSUE THREAD

**Issue by mmilata** [xzfc/cached-nix-shell#28]
nix-shell seems to have pipefail set (`set -o pipefail`) while cached-nix-shell does not:
```
$ nix-shell -p moreutils --run "false" ; echo $?
1
$ nix-shell -p moreutils --run "false | ts -s" ; echo $?
1
$ cached-nix-shell -p moreutils --run "false" ; echo $?
1
$ cached-nix-shell -p moreutils --run "false | ts -s" ; echo $?
0
```

**Comment by xzfc** [comment]
Added preserving of some shellopts/bashopts that are touched by stdenv/original nix-shell. I think these should be enough since nix expressions generally don't change it beyond what `stdenv/setup.sh` does, but if anything, we could add code to handle every possible option.
