### ISSUE TITLE
Some nix-shell options are rejected

### ISSUE THREAD

**Issue by nh2** [xzfc/cached-nix-shell#3]
Hi, I'm passing `-j4` and `--option extra-substituters ...` to nix-shell, but `cached-nix-shell` rejects them, so it is not a drop-in replacement for me.

Could it accept those?

Thanks!

**Comment by xzfc** [comment]
Added in 52b25cf55c40a8c0e1c28c0ad182077e910bbec1.

You can use `-j 4` for now, I'll add concise syntax (`-j 4` → `-j4`) later.

**Comment by nh2** [comment]
Thanks!
