### ISSUE TITLE
Changing command prompt when inside shell

### ISSUE THREAD

**Issue by Zimmi48** [xzfc/cached-nix-shell#4]
Hello,

Thank you for providing this tool. Long wait-times to run `nix-shell` have always been a major source of pain to me.

One thing that I appreciate about `nix-shell` that I don't find in `cached-nix-shell` is the fact that the command prompt changes when inside the shell. It helps to know that we are in a modified environment. Is there a way to configure this?

Thanks!

**Comment by xzfc** [comment]
I've added default PS1 in ade493239d20458658db6b994a9bc40724e67ebb. It looks like this: `[cached-nix-shell:/home/user]$ `.
You can customize it using this trick: https://github.com/NixOS/nix/issues/1268#issuecomment-449661822.

**Comment by Zimmi48** [comment]
Thanks!
