### ISSUE TITLE
`--show-trace` and other diagnostics flags not supported

### ISSUE THREAD

**Issue by timbertson** [xzfc/cached-nix-shell#7]
Does it make sense to just pass all unknown options though to `nix-shell`? I guess the cache logic might have to consider the argument set given (in terms of whether it changes the resulting environment), but I assume there's a bunch that would be safe to pass through, e.g:

```
--show-trace
--verbose
--quiet
--timeout VALUE
--fallback
--option KEY VALUE
```

**Comment by xzfc** [comment]
C-n-s needs at least to know how many arguments each option takes. Сonsider `nix-shell -p --argstr x --run bash`, `--run` here isn't an option but rather a string argument for `--argstr`.

**Comment by xzfc** [comment]
Added a bunch of options in 137390213d0b6cedce5f618f3141e69aeeae797c. Most of them do not invalidate the cache.
